# tasks/configure_webserver.yml
---
- name: Copy Web Server Configuration
  template:
    src: webserver.conf.j2
    dest: /etc/{{ webserver_service }}/sites-available/default

- name: Ensure Web Server Config is Enabled
  file:
    src: /etc/{{ webserver_service }}/sites-available/default
    dest: /etc/{{ webserver_service }}/sites-enabled/default
    state: link

- name: Remove Default Web Root
  file:
    path: /var/www/html/index.html
    state: absent
