---
- hosts: webservers
  tasks:
    - name: Authenticate with Docker Hub
      command: sudo docker login -u "dockerhub25" -p "docker@25"
      when: docker_hub_username is defined and docker_hub_password is defined
    - name: Clone repository
      git:
        repo: https://github.com/saidhuljohny2/Cafe-App.git
        dest: /opt/docker/cafe-app
        clone: yes
        update: yes

    - name: Create Docker image
      command: sudo docker build -t cafe-app:latest /opt/docker/cafe-app
      args:
        chdir: /opt/docker/
    - name: Create tag to push image onto Docker Hub
      command: sudo docker tag cafe-app:latest dockerhub25/cafe-app:latest

    - name: Push Docker image
      command: sudo docker push dockerhub25/cafe-app:latest
      when: docker_hub_username is defined and docker_hub_password is defined
