- hosts: localhost
  become: yes  # This will run the tasks with sudo privileges, so you don't need to use 'sudo' in each command

  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/saidhuljohny2/Cafe-App.git
        dest: /opt/docker/cafe-app
        clone: yes
        update: yes

    - name: Create Docker image
      command: docker build -t cafe-app:latest /opt/docker/cafe-app
      args:
        chdir: /opt/docker/

    - name: Create tag to push image onto Docker Hub
      command: docker tag cafe-app:latest saidhuljohny2/cafe-app:latest

    - name: Push Docker image
      command: docker push saidhuljohny2/cafe-app:latest
