---
- name: Configure Apache2 and Create Sample Website
  hosts: webservers  # Replace with the name of your target host or group
  become: yes  # To run tasks as sudo

  tasks:
    - name: Update package cache (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install Apache2
      package:
        name: apache2
        state: present

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a sample index.html file
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
