steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thermal-micron-396706/myimage', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thermal-micron-396706/myimage']
# Deploy container image to Cloud Run with a 50% traffic split
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'CloudRunwithCICD'
    - '--image'
    - 'gcr.io/thermal-micron-396706/myimage'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--traffic'
    - 'latest=50'
images:
- gcr.io/thermal-micron-396706/myimage
