steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thermal-micron-396706/myimage', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thermal-micron-396706/myimage']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'cloudrunwithcicd'
    - '--image'
    - 'gcr.io/thermal-micron-396706/myimage'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
images:
- gcr.io/thermal-micron-396706/myimage
