---
- hosts: kubernetes
  user: root

  tasks:
    - name: deploy cafeapp on kubernetes
      command: sudo kubectl apply -f cafe-app-deployment.yml

    - name: create service for cafeapp
      command: sudo kubectl apply -f cafe-app-service.yml

    - name: update deployment with new pods if image updated in docker hub
      command: sudo kubectl rollout restart deployment.apps/mylab-cafe-app